SELECT C.ITEM_ID, C.ITEM_NAME, C.RARITY
-- 업그레이드 전의 아이템 조회
FROM ITEM_INFO A JOIN ITEM_TREE B ON A.ITEM_ID = B.PARENT_ITEM_ID
-- 업그레이드 후의 아이템 조회
JOIN ITEM_INFO C ON C.ITEM_ID = B.ITEM_ID
WHERE A.RARITY = 'RARE'
ORDER BY C.ITEM_ID DESC